### ISSUE TITLE
Autogenerate id's ecto-2 branch

### ISSUE THREAD

**Issue by merqlove** [michalmuskala/mongodb_ecto#107]
I have such constriction within Phoenix `web.ex`
Seems that @primary_key not works as expected...

```
  def id_model do
    quote do
      use InFactApi.Web, :model
      @primary_key {:id, :binary_id, autogenerate: true}
      @foreign_key_type :binary_id
    end
  end

  def model do
    quote do
      use Ecto.Schema

      import Ecto
      import Ecto.Changeset
      import Ecto.Query, only: [from: 1, from: 2]
    end
  end
```

```
defmodule InFactApi.Result do
  use InFactApi.Web, :id_model

  embedded_schema do
    field :suggested, {:array, :string}, default: []
    field :found, {:array, :string}, default: []
  end

#...

end
```

Error:

```
 struct `%InFactApi.Result{found: ["bbb", "ccc", "ddd"], id: nil, ...}` is missing primary key value
```

It is on saving:

```
%InFactApi.Result{  
      suggested: ["aaa", "bbb", "ccc"],
      found: ["bbb", "ccc", "ddd"]
    }
```

**Comment by michalmuskala** [comment]
That's very strange because we have exactly those cases in the integration suite, and it passes without issues. Can you show the full error?

**Comment by merqlove** [comment]
Yeah, with similar but simpler model it is something like this:

```
22:11:53.596 [error] GenServer :standard_analytic_pipeline terminating
** (Ecto.NoPrimaryKeyValueError) struct `%InFactApi.ExpertiseArticle{article: #Ecto.Association.NotLoaded<association :article is not loaded>, article_id: "58a204f944c6c308d8b39732", id: nil, iteration: 1}` is missing
primary key value
    (ecto) lib/ecto/embedded.ex:139: anonymous fn/3 in Ecto.Embedded.autogenerate_id/5
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/embedded.ex:138: Ecto.Embedded.autogenerate_id/5
    (ecto) lib/ecto/embedded.ex:105: Ecto.Embedded.to_struct/4
    (ecto) lib/ecto/embedded.ex:76: anonymous fn/5 in Ecto.Embedded.prepare_each/4
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/embedded.ex:74: Ecto.Embedded.prepare_each/4

    (ecto) lib/ecto/embedded.ex:59: anonymous fn/5 in Ecto.Embedded.prepare/4
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/map.ex:513: Map.update!/3
    (ecto) lib/ecto/embedded.ex:102: Ecto.Embedded.to_struct/4
    (ecto) lib/ecto/embedded.ex:76: anonymous fn/5 in Ecto.Embedded.prepare_each/4
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/embedded.ex:74: Ecto.Embedded.prepare_each/4
    (ecto) lib/ecto/embedded.ex:59: anonymous fn/5 in Ecto.Embedded.prepare/4
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/map.ex:513: Map.update!/3
    (ecto) lib/ecto/embedded.ex:102: Ecto.Embedded.to_struct/4
    (ecto) lib/ecto/embedded.ex:59: anonymous fn/5 in Ecto.Embedded.prepare/4
    (stdlib) lists.erl:1263: :lists.foldl/3
Last message: {:query_search_query_error, {"479fa438-f220-11e6-8081-685b35999bd2", %InFactApi.ExpertiseQuery{articles: [%InFactApi.ExpertiseArticle{article: #Ecto.Association.NotLoaded<association :article is not loade
d>, article_id: "58a204f944c6c308d8b39722", id: nil, iteration: 1}, ...}

**Comment by merqlove** [comment]
Looks like  it is at:
```lib/ecto/embedded.ex:139: anonymous fn/3 in Ecto.Embedded.autogenerate_id/5```

**Comment by merqlove** [comment]
Seems i understand what's doing.
Looks like it's because ExMachina don't run any changesets...

**Comment by merqlove** [comment]
Closed, it is ExMachina behavior.
