### ISSUE TITLE
Unable to run tests, on a new phx 1.3-rc2 app on the ecto-2.1 branch

### ISSUE THREAD

**Issue by zeroasterisk** [michalmuskala/mongodb_ecto#127]
Working in dev mode, and in `iex` no problem - but tests not running

```ex
# config/test.ex
config :myapp, Myapp.Repo,
  adapter: Mongo.Ecto,
  database: "myapp_test",
  hostname: "localhost"
```

and I get this:

```
$ mix test
Compiling 27 files (.ex)
Generated myapp app
** (RuntimeError) cannot configure sandbox with pool nil.
To use the SQL Sandbox, configure your repository pool as:

      pool: Ecto.Adapters.SQL.Sandbox

    (ecto) lib/ecto/adapters/sql/sandbox.ex:429: Ecto.Adapters.SQL.Sandbox.mode/2
    (elixir) lib/code.ex:370: Code.require_file/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (mix) lib/mix/tasks/test.ex:229: Mix.Tasks.Test.run/1
```

I tried specifying a pool:

```ex
# config/test.ex
config :myapp, Myapp.Repo,
  adapter: Mongo.Ecto,
  database: "myapp_test",
  hostname: "localhost",
  pool: Mongo.Pool.Poolboy
```

```
$ mix test
Compiling 27 files (.ex)
Generated myapp app
** (UndefinedFunctionError) function Mongo.Pool.Poolboy.ensure_all_started/2 is undefined (module Mongo.Pool.Poolboy is not available)
    Mongo.Pool.Poolboy.ensure_all_started([pool_timeout: 5000, timeout: 15000, adapter: Mongo.Ecto, database: "myapp_test", hostname: "localhost", pool: Mongo.Pool.Poolboy], :temporary)
    lib/mongo_ecto.ex:425: Mongo.Ecto.ensure_all_started/2
    (ecto) lib/mix/ecto.ex:84: Mix.Ecto.ensure_started/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:72: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:645: Enum.each/2
    (mix) lib/mix/task.ex:300: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:332: Mix.Task.run_alias/3
```

----

What's interesting is that I do see some connection to the mongo instance when tests happen...  

----

### replication instructions 

```
git clone https://github.com/zeroasterisk/example-elixir-meteor-api.git
cd example-elixir-meteor-api
git checkout ecto-2.1
mix deps.get
mix test
```

**Comment by zeroasterisk** [comment]
Nevermind - I found it (of course, after I posted this issue)

```ex
# test/test_helper.ex
Ecto.Adapters.SQL.Sandbox.mode(Eltoroportal.Repo, :manual)
```

replaced it with stuff copied from: 
https://github.com/michalmuskala/mongodb_ecto/blob/8890d5418f33dab9886911bf86c9254e89bbe582/test/test_helper.exs#L23

thanks!!

**Comment by ankhers** [comment]
I should note that the 2.1 branch is still a ways off from being ready.

**Comment by zeroasterisk** [comment]
I take it back, I can't run tests, it no longer stops me from running a test, but it does failout on every test, unable to get to the DB:

```


  1) test users list_users/0 returns all users (Myappportal.AccountsTest)
     test/myappportal/accounts/accounts_test.exs:22
     ** (exit) exited in: GenServer.call(Myappportal.Repo.Pool, {:checkout, [repo: Myappportal.Repo, sandbox_pool: DBConnection.Poolboy, ownership_pool: Ecto.Adapters.SQL.Sandbox.Pool, pool_timeout: 5000, timeout: 15000, adapter: Mongo.Ecto, database: "myappportal_test", hostname: "localhost"]}, 5000)
         ** (EXIT) an exception was raised:
             ** (FunctionClauseError) no function clause matching in DBConnection.Connection.handle_call/3
                 (db_connection) lib/db_connection/connection.ex:192: DBConnection.Connection.handle_call({:checkout, [repo: Myappportal.Repo, sandbox_pool: DBConnection.Poolboy, ownership_pool: Ecto.Adapters.SQL.Sandbox.Pool, pool_timeout: 5000, timeout: 15000, adapter: Mongo.Ecto, database: "myappportal_test", hostname: "localhost"]}, {#PID<0.320.0>, #Reference<0.0.3.856>}, %{after_connect: nil, after_connect_timeout: 15000, after_timeout: :backoff, backoff: %DBConnection.Backoff{max: 30000, min: 1000, state: {1000, 10000, {:rand, {%{max: 288230376151711743, next: #Function<8.41921595/1 in :rand.mk_alg/1>, type: :exsplus, uniform: #Function<9.41921595/1 in :rand.mk_alg/1>, uniform_n: #Function<10.41921595/2 in :rand.mk_alg/1>}, [163830081607087721 | 124282697845450076]}}}, type: :rand_exp}, broker: nil, client: nil, idle: :passive, idle_time: 0, idle_timeout: 1000, lock: nil, mod: Mongo.Protocol, opts: [name: Myappportal.Repo.Pool, otp_app: :myappportal, repo: Myappportal.Repo, adapter: Mongo.Ecto, database: "myappportal_test", hostname: "localhost", pool_timeout: 5000, timeout: 15000, adapter: Mongo.Ecto, database: "myappportal_test", hostname: "localhost"], queue: {[], []}, regulator: nil, state: %{database: "myappportal_test", request_id: 0, socket: {:gen_tcp, #Port<0.8275>}, ssl: false, timeout: 15000, wire_version: 5, write_concern: %{w: 1}}, timer: nil})
                 (connection) lib/connection.ex:488: Connection.handle_call/3
                 (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     stacktrace:
       (elixir) lib/gen_server.ex:737: GenServer.call/3
       (db_connection) lib/db_connection/ownership.ex:58: DBConnection.Ownership.ownership_checkout/2
       (ecto) lib/ecto/adapters/sql/sandbox.ex:477: Ecto.Adapters.SQL.Sandbox.checkout/2
       (myappportal) test/support/data_case.ex:29: Myappportal.DataCase.__ex_unit_setup_0/1
       (myappportal) test/support/data_case.ex:1: Myappportal.DataCase.__ex_unit__/2
       test/myappportal/accounts/accounts_test.exs:1: Myappportal.AccountsTest.__ex_unit__/2
```

**Comment by zeroasterisk** [comment]
@ankhers would you not recommend me use this branch?  I've started a phx 1.3-rc2 project which needs to connect to a legacy mongo db... what branch would you recommend at this point?

**Comment by scottmessinger** [comment]
@zeroasterisk the ecto-2 branch has been working pretty well for me.

**Comment by zeroasterisk** [comment]
@scottmessinger I'm trying to use phx-rc2 (because I like living in the near future)

I can not use the `ecto-2` branch w/ `ecto 2.1`

```
Dependencies have diverged:
* ecto (https://github.com/elixir-ecto/ecto.git)
  different specs were given for the ecto app:

  > In deps/mongodb_ecto/mix.exs:
    {:ecto, "~> 2.0.0", [env: :prod, git: "https://github.com/elixir-ecto/ecto.git", ref: "v2.0", manager: :mix]}

  > In deps/phoenix_ecto/mix.exs:
    {:ecto, "~> 2.1", [env: :prod, hex: "ecto", repo: "hexpm", optional: false]}
```

**Comment by ankhers** [comment]
You will need to lower the version of Ecto that is being used if you want to use Mongo. I am doing this in one of my phoenix applications because we have not quite fixed up this adapter for use with 2.1 yet.

Unfortunately, I am unsure of a timeframe for when the work in #123 will be ready to be used. If you have some spare time, would you consider helping the effort?

**Comment by zeroasterisk** [comment]
I'm happy to help, but this is my first elixir project.  

I've got to use mongo.  I want to use the new/next phoenix because it feels like it's ready for release and I don't want to have to re-build later.  That's why I'm motivated _(and annoying)_.

**Comment by ankhers** [comment]
Like I said, you can already use phoenix 1.3 with this adapter. You just need to lower the version of Ecto that is being used within your application.

Any help would be appreciated.

**Comment by zeroasterisk** [comment]
ok - thanks for the communication and help.

I'm reverting to the `ecto-2` branch.  The above PR #128 is the result of my having to play w/ versions to make them play nice (with `peonix_ecto`)

I'll also be happy to help out with the `ecto-2.1` branch, however I can... got a task-list?

**Comment by zeroasterisk** [comment]
@scottmessinger it looks like you have some good stuff on your fork:
[master](https://github.com/michalmuskala/mongodb_ecto/compare/master...scottmessinger:master?expand=1)
[ecto-2.1](https://github.com/michalmuskala/mongodb_ecto/compare/ecto-2.1...scottmessinger:ecto-2.1.0?expand=1)

is your master stuff about the DB for testing?

is your ecto-2.1 stuff ready to use?  are you collaborating with @ankhers ?

**Comment by ankhers** [comment]
I'm going to close this as you were trying to use a version of this adapter that is still in active development and has a lot of work left to be done on it. And you opened #129.
