### ISSUE TITLE
Unable to run tests, on a new phoenix 1.3 app on the ecto-2 branch

### ISSUE THREAD

**Issue by zeroasterisk** [michalmuskala/mongodb_ecto#129]
this is just like issue #127 except that I'm on ecto-2 

* phoenix_ecto 3.0.1 (https://github.com/phoenixframework/phoenix_ecto.git) (mix)
  locked at b762682 (ref)
  ok
* mongodb_ecto 0.1.4 (https://github.com/zeroasterisk/mongodb_ecto.git) (mix)
  locked at 4f80662 (branch: elixir-ecto-v2.0.1)
  ok

```
$ mix test

  1) test renders 404.html (Meteorappapi.ErrorViewTest)
     test/views/error_view_test.exs:7
     ** (exit) exited in: GenServer.call(Meteorappapi.Repo.Pool, {:checkout, [repo: Meteorappapi.Repo, sandbox_pool: DBConnection.Poolboy, ownership_pool: Ecto.Adapters.SQL.Sandbox.Pool, pool_timeout: 5000, timeout: 15000, adapter: Mongo.Ecto, database: "meteorappapi_test", hostname: "localhost"]}, 5000)
         ** (EXIT) an exception was raised:
             ** (FunctionClauseError) no function clause matching in DBConnection.Connection.handle_call/3
                 (db_connection) lib/db_connection/connection.ex:192: DBConnection.Connection.handle_call({:checkout, [repo: Meteorappapi.Repo, sandbox_pool: DBConnection.Poolboy, ownership_pool: Ecto.Adapters.SQL.Sandbox.Pool, pool_timeout: 5000, timeout: 15000, adapter: Mongo.Ecto, database: "meteorappapi_test", hostname: "localhost"]}, {#PID<0.876.0>, #Reference<0.0.5.3631>}, %{after_connect: nil, after_connect_timeout: 15000, after_timeout: :backoff, backoff: %DBConnection.Backoff{max: 30000, min: 1000, state: {1000, 10000, {:rand, {%{max: 288230376151711743, next: #Function<8.41921595/1 in :rand.mk_alg/1>, type: :exsplus, uniform: #Function<9.41921595/1 in :rand.mk_alg/1>, uniform_n: #Function<10.41921595/2 in :rand.mk_alg/1>}, [218764395245907230 | 213613729924590392]}}}, type: :rand_exp}, broker: nil, client: nil, idle: :passive, idle_time: 0, idle_timeout: 1000, lock: nil, mod: Mongo.Protocol, opts: [name: Meteorappapi.Repo.Pool, otp_app: :meteorappapi, repo: Meteorappapi.Repo, adapter: Mongo.Ecto, database: "meteorappapi_test", hostname: "localhost", pool_timeout: 5000, timeout: 15000, adapter: Mongo.Ecto, database: "meteorappapi_test", hostname: "localhost"], queue: {[], []}, regulator: nil, state: %{database: "meteorappapi_test", request_id: 0, socket: {:gen_tcp, #Port<0.35920>}, ssl: false, timeout: 15000, wire_version: 5, write_concern: %{w: 1}}, timer: nil})
                 (connection) lib/connection.ex:488: Connection.handle_call/3
                 (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
                 (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
                 (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
     stacktrace:
       (elixir) lib/gen_server.ex:737: GenServer.call/3
       (db_connection) lib/db_connection/ownership.ex:58: DBConnection.Ownership.ownership_checkout/2
       (ecto) lib/ecto/adapters/sql/sandbox.ex:477: Ecto.Adapters.SQL.Sandbox.checkout/2
       (meteorappapi) test/support/conn_case.ex:36: Meteorappapi.ConnCase.__ex_unit_setup_0/1
       (meteorappapi) test/support/conn_case.ex:1: Meteorappapi.ConnCase.__ex_unit__/2
       test/views/error_view_test.exs:1: Meteorappapi.ErrorViewTest.__ex_unit__/2
```

### replication instructions

```
git clone https://github.com/zeroasterisk/example-elixir-meteor-api.git
cd example-elixir-meteor-api
git checkout ecto-2
mix deps.get
mix test
```

https://github.com/zeroasterisk/example-elixir-meteor-api/blob/ecto-2/config/test.exs

**Comment by ankhers** [comment]
I have not tried it myself, but I would guess that this adapter does not support using the SQL sandbox. Try removing that and let me know if that works.

**Comment by zeroasterisk** [comment]
I found that the phoenix code generated a lot of test files (in addition to the test helper) which mentioned the SQL sandbox.

I commented out all code which did mention Sandbox and this went away... 

This is likely to be a problem for other novices trying to make mongo and phoenix play nice...
