### ISSUE TITLE
Error: Mongo.Ecto.all/5

### ISSUE THREAD

**Issue by scottmessinger** [michalmuskala/mongodb_ecto#27]
First, thanks for your hard work on this! Second, I ran into a problem getting things set up a in a new Phoenix project. I created a model and navigated in Chrome to the route I set up for the endpoint. I then got this error:

```
[error] #PID<0.1553.0> running CommonStandardsProject.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /api/jurisdictions
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function: Mongo.Ecto.all/5
        (mongodb_ecto) Mongo.Ecto.all(CommonStandardsProject.Repo, #Ecto.Query<from j in CommonStandardsProject.Jurisdiction, select: j>, [], #Function<0.119612849/2 in Ecto.Repo.Queryable.preprocess/2>, [])
        (ecto) lib/ecto/repo/queryable.ex:21: Ecto.Repo.Queryable.all/4
        web/controllers/jurisdiction_controller.ex:9: CommonStandardsProject.JurisdictionController.index/2
        web/controllers/jurisdiction_controller.ex:1: CommonStandardsProject.JurisdictionController.phoenix_controller_pipeline/2
        (common_standards_project) lib/phoenix/router.ex:281: CommonStandardsProject.Router.dispatch/2
        (common_standards_project) web/router.ex:1: CommonStandardsProject.Router.do_call/2
        (common_standards_project) lib/common_standards_project/endpoint.ex:1: CommonStandardsProject.Endpoint.phoenix_endpoint_pipeline/1
        (common_standards_project) lib/plug/debugger.ex:90: CommonStandardsProject.Endpoint."call (overridable 3)"/2
```

Is this something I've done or a bug in the library? Here's the repo: https://github.com/scottmessinger/elixir-api-spike

**Comment by michalmuskala** [comment]
That's a problem with Ecto versions. José introduced yesterday breaking change for the Mongo adapter, and I haven't got time to implement it yet. I'll be rolling a commit with a fix shortly.

**Comment by scottmessinger** [comment]
Thanks!
