### ISSUE TITLE
Error while updating a single record

### ISSUE THREAD

**Issue by pma** [michalmuskala/mongodb_ecto#34]
I'm getting this error while trying to update a single record with mongodb_ecto:

```elixir
iex(1)> rec = Simple.Repo.get(Weather, "1d4197db0398eb193c5315cd")
iex(2)> Simple.Repo.update!(Ecto.Changeset.change(rec, temp_hi: 50))
** (FunctionClauseError) no function clause matching in Mongo.Ecto.update/7
    (mongodb_ecto) lib/mongo_ecto.ex:459: Mongo.Ecto.update(Simple.Repo, {nil, "weather", Weather}, [temp_hi: 50, updated_at: {{2015, 7, 26}, {9, 53, 9, 0}}], [id: %Ecto.Query.Tagged{tag: nil, type: :binary_id, value: <<29, 65, 151, 219, 3, 152, 235, 25, 60, 83, 21, 205>>}], nil, [], [])
            (ecto) lib/ecto/repo/model.ex:116: anonymous fn/11 in Ecto.Repo.Model.update/4
            (ecto) lib/ecto/repo/model.ex:25: Ecto.Repo.Model.update!/4
```

Using Ecto with Postgresql it works:

```elixir
iex(1)> rec = Simple.Repo.get(Weather, 1)
iex(2)> Simple.Repo.update!(Ecto.Changeset.change(rec, temp_hi: 50))                      
%Weather{__meta__: %Ecto.Schema.Metadata{source: {nil, "weather"},
  state: :loaded},
 city: #Ecto.Association.NotLoaded<association :city is not loaded>,
 city_id: nil, id: 1, inserted_at: #Ecto.DateTime<2015-07-26T09:39:45Z>,
 prcp: 0.0, temp_hi: 50, temp_lo: 23,
 updated_at: #Ecto.DateTime<2015-07-26T09:52:40Z>}
```

This is with master mongodb_ecto (commit 9b07403552f3f48cfd298a6e3fa5b637de2ef3ab) and ecto  (commit a19072ba9ca1ffa0b440578a7e345bf9a582f344).

I'm using Mongo version 3.0.4

**Comment by josevalim** [comment]
Please include both Ecto and Mongo.Ecto versions in the report. :)

**Comment by pma** [comment]
@josevalim sorry. issue updated to include versions used

**Comment by michalmuskala** [comment]
This is indeed related to the ecto version. I pinned down the commit I'm sure the adapter works correctly with.

**Comment by pma** [comment]
@michalmuskala With a clean clone of the adapter I still get the error. What am I missing?

The steps I'm using are:

```
$ git clone git@github.com:michalmuskala/mongodb_ecto.git
$ cd mongodb_ecto
$ mix deps.get
$ cd examples/simple/
$ mix deps.get
$ iex -S mix
```

```elixir
iex(1)> rec = Simple.Repo.get(Weather, "1d4197db0398eb193c5315cd")
iex(2)>  Simple.Repo.update!(Ecto.Changeset.change(rec, temp_hi: 50))
** (FunctionClauseError) no function clause matching in Mongo.Ecto.update/7
    (mongodb_ecto) lib/mongo_ecto.ex:453: Mongo.Ecto.update(Simple.Repo, {nil, "weather", Weather}, [temp_hi: 50, updated_at: {{2015, 7, 26}, {11, 43, 2, 0}}], [id: %Ecto.Query.Tagged{tag: nil, type: :binary_id, value: <<29, 65, 151, 219, 3, 152, 235, 25, 60, 83, 21, 205>>}], nil, [], [])
            (ecto) lib/ecto/repo/model.ex:116: anonymous fn/11 in Ecto.Repo.Model.update/4
            (ecto) lib/ecto/repo/model.ex:25: Ecto.Repo.Model.update!/4
```

I confirmed that the checked out ecto in mongodb_ecto/deps/ecto is at `a19072b...`, as specified in mix.exs and mix.lock of mongodb_ecto.

**Comment by michalmuskala** [comment]
It was my mistake, as I pushed the fix to a wrong branch. My git fu failed me, I'm sorry.
