### ISSUE TITLE
Error when change primary_key to _id

### ISSUE THREAD

**Issue by phongmh307** [michalmuskala/mongodb_ecto#53]
For legacy reason, I have to use a customized string for my Mongo `_id`
This error happened after that

```
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mongo.Ecto.update/7
        (mongodb_ecto) lib/mongo_ecto.ex:483: Mongo.Ecto.update(App.Repo, %{context: nil, model: App.Tracking, source: {nil, "trackings"}, state: :loaded}, [current_status: "picked_up", external_carrier: "VTP", external_tracking: "SNPE37043100000186", updated_at: {{2015, 12, 8}, {21, 3, 49, 0}}], [_id: "E37043100000186"], nil, [], [])
        (ecto) lib/ecto/repo/model.ex:253: Ecto.Repo.Model.apply/4
        (ecto) lib/ecto/repo/model.ex:152: anonymous fn/10 in Ecto.Repo.Model.do_update/4
        (ecto) lib/ecto/repo/model.ex:25: Ecto.Repo.Model.update!/4
```

My schema:
```
defmodule App.Tracking do
  use App.Web, :model

  @primary_key {:_id, :string, []}
  @derive {Phoenix.Param, key: :_id}
  @derive {Poison.Encoder, only: [
    :_id, :is_external, :external_carrier, :external_tracking, :business_id,
    :current_status, :balance_adjustment, :inserted_at, :updated_at, :modifications
  ]}
  schema "trackings" do
    field :is_external,           :boolean, default: false
    field :external_carrier,      :string
    field :external_tracking,     :string
    field :current_status,        :string
    field :balance_adjustment,    :integer
    field :business_id,           :binary_id
    
    embeds_many :modifications, App.PackageModification
    
    timestamps
  end

  @required_fields ~w(_id is_external current_status balance_adjustment)
  @optional_fields ~w(external_carrier external_tracking business_id modifications business_id)

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end
```

**Comment by michalmuskala** [comment]
The adapter is assuming ids are Mongo's ObjectID. I'm not exactly sure how it would handle other things...

I can roll an immediate fix for the issue you have, but I'm not sure there won't be more to follow. It's hard to say without investigating this more thoroughly.

**Comment by michalmuskala** [comment]
Could you try master and see if that fixes your problem?

**Comment by phongmh307** [comment]
Thank you so much. It works perfectly now. I will let you now if any issue happens after this
