### ISSUE TITLE
(Ecto.ConstraintError) constraint error when attempting to insert model: * unique: _id_

### ISSUE THREAD

**Issue by sevfurneaux** [michalmuskala/mongodb_ecto#55]
I've been reading [Platformatec's guide on adding embedded models](http://blog.plataformatec.com.br/2015/08/working-with-ecto-associations-and-embeds/). However, I am getting a constraint error when I try and insert the new embeds via changesets using Mongo.Ecto.

This is what I followed in the guide:

```
defmodule MyApp.Permalink do
  use Ecto.Model

  embedded_schema do
    field :url
    timestamps
  end
end

defmodule MyApp.Post do
  use Ecto.Model

  schema "posts" do
    field :title
    field :body
    has_many :comments, MyApp.Comment
    embeds_many :permalinks, MyApp.Permalink
    timestamps
  end
end

# Generate a changeset for the post
changeset = Ecto.Changeset.change(post)

# Let's track the new permalinks
changeset = Ecto.Changeset.put_change(changeset, :permalinks,
  [%Permalink{url: "example.com/thebest"},
   %Permalink{url: "another.com/mostaccessed"}]
)

# Now let's insert the post with permalinks at once!
post = Repo.insert!(changeset)
```

I get the following error when I `post = Repo.insert!(changeset)`:

```
iex(8)> post = MyApp.Repo.insert!(changeset)
[debug] INSERT coll="posts" document=[body: "This is the body", _id: #BSON.ObjectId<1dfafe19149351241a15b1b1>, inserted_at: #BSON.DateTime<2015-12-09T14:58:33Z>, permalinks: [[_id: #BSON.ObjectId<1dfb04191493512880ee927d>, inserted_at: #BSON.DateTime<2015-12-09T15:24:09Z>, updated_at: #BSON.DateTime<2015-12-09T15:24:09Z>, url: "example.com/thebest"], [_id: #BSON.ObjectId<1dfb04191493512880ee927e>, inserted_at: #BSON.DateTime<2015-12-09T15:24:09Z>, updated_at: #BSON.DateTime<2015-12-09T15:24:09Z>, url: "another.com/mostaccessed"]], title: "Test Post", updated_at: #BSON.DateTime<2015-12-09T14:58:33Z>] [] ERROR query=0.7ms
** (Ecto.ConstraintError) constraint error when attempting to insert model:

    * unique: _id_

If you would like to convert this constraint into an error, please
call unique_constraint/3 in your changeset and define the proper
constraint name. The changeset has not defined any constraint.

      (ecto) lib/ecto/repo/model.ex:274: anonymous fn/5 in Ecto.Repo.Model.constraints_to_errors/3
    (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
      (ecto) lib/ecto/repo/model.ex:91: anonymous fn/10 in Ecto.Repo.Model.do_insert/4
      (ecto) lib/ecto/repo/model.ex:14: Ecto.Repo.Model.insert!/4
```

Was unsure whether this was a bug, or something I have done wrong?

Thanks!

**Comment by michalmuskala** [comment]
I can't really reproduce it. I've created an example project with embedded models here: https://github.com/michalmuskala/mongodb_ecto/blob/embedded_example/examples/embedded_models/lib/embedded_models.ex

Is there something different in your setup? Do you have indexes on your database?

**Comment by sevfurneaux** [comment]
Thanks Michał. Your version works perfectly.

I'm getting the error I previously mentioned when starting a new Phoenix app with mongodb defined. I'll retrace my steps and will follow up in detail.

**Comment by michalmuskala** [comment]
@sevfurneaux Did you manage to resolve your problem?

**Comment by sachinbhutani** [comment]
@sevfurneaux , I am getting the same error even for top-level (non embedded) models. Even after using unique_constraint(:fieldname) in the changeset. 

I created a new app with phoenix.new .... --mongodb and created the unique index on the table using mongo shell.

**Comment by merqlove** [comment]
it's by Ecto design. You cannot use such constraints with embeds.

**Comment by michalmuskala** [comment]
Since there was no activity here for a long time, I'm going to close this. If the issue is still relevant feel free to reopen or ping.
