### ISSUE TITLE
mix ecto.migrate gives an error because of callback in ecto

### ISSUE THREAD

**Issue by blacksails** [michalmuskala/mongodb_ecto#56]
I get the following error when running `mix ecto.migrate`. I think the migration works as it should, but the command gives an error exitcode. This is a problem for me when I build do builds.

```
mix ecto.migrate

19:16:03.206 [info]  == Running MyApp.Repo.Migrations.CreatePosts.change/0 forward

19:16:03.208 [info]  == Migrated in 0.0s
** (UndefinedFunctionError) undefined function: Mongo.Ecto.stop/2
    (mongodb_ecto) Mongo.Ecto.stop(#PID<0.151.0>, 5000)
    (ecto) lib/mix/ecto.ex:75: Mix.Ecto.ensure_stopped/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by michalmuskala** [comment]
@blacksails could you try with current master?

**Comment by blacksails** [comment]
will do :+1:

**Comment by blacksails** [comment]
Works like a charm. Good job :)

**Comment by brado** [comment]
I am having the same problem: 

```
$ mix ecto.migrate

15:10:41.178 [info]  Already up
** (UndefinedFunctionError) undefined function Mongo.Ecto.stop/3
    (mongodb_ecto) Mongo.Ecto.stop(MyApp.Repo, #PID<0.176.0>, 5000)
    (ecto) lib/mix/ecto.ex:94: Mix.Ecto.ensure_stopped/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

In my mix.exs of my Phoenix Framework project, I'm pulling what based on the version listed in this repo's source should be the master: 

```
{:mongodb_ecto, ">= 0.1.2"}
```

I've cleaned and pulled dependencies again, but the same thing occurs. Is there some other way to get the master into a Phoenix project?

**Comment by brado** [comment]
Note on my above post...I have now changed my dependency to this: 

```
      {:mongodb_ecto, github: "michalmuskala/mongodb_ecto"},
```

And re-pulled dependencies, and I'm still getting exactly the same error.

**Comment by brado** [comment]
I suppose I should have listed all of my dependencies....here they are: 

```
  defp deps do
    [
      {:phoenix, "~> 1.1"},
      {:phoenix_ecto, "~> 2.0"},
      {:phoenix_html, "~> 2.3"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:mongodb_ecto, github: "michalmuskala/mongodb_ecto"},
#      {:mongodb_ecto, "~> 0.1.2"},
      {:cowboy, "~> 1.0"},
      {:exrm, "~> 1.0.0-rc7"},
      {:gettext, "~> 0.9"}
    ]
  end
```

**Comment by jasmo2** [comment]
I am still getting the same error.
