### ISSUE TITLE
How to use Elixir ~> 1.3

### ISSUE THREAD

**Issue by kevinblade** [michalmuskala/mongodb_ecto#93]
Hi! I want to use shield package + mongodb_ecto on elixir ~> 1.3.2 for my project.
But I encountered following error.

```
[error] #PID<0.665.0> running CoodApiService.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /users/register
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Logger.Utils.truncate_n/2
        (logger) lib/logger/utils.ex:20: Logger.Utils.truncate_n(#Function<0.51900625/1 in Mongo.Ecto.Connection.log/2>, 8078)
        (logger) lib/logger/utils.ex:49: Logger.Utils.truncate_n_list/3
        (logger) lib/logger/utils.ex:16: Logger.Utils.truncate/2
        (logger) lib/logger.ex:486: Logger.bare_log/3
        (ecto) lib/ecto/log_entry.ex:41: Ecto.LogEntry.log/1
        (db_connection) lib/db_connection.ex:966: DBConnection.log/6
        (mongodb) lib/mongo.ex:297: Mongo.insert_one/4
        (mongodb_ecto) lib/mongo_ecto/connection.ex:108: Mongo.Ecto.Connection.insert/3
        (mongodb_ecto) lib/mongo_ecto.ex:515: Mongo.Ecto.insert/5
        (ecto) lib/ecto/repo/schema.ex:397: Ecto.Repo.Schema.apply/4
        (ecto) lib/ecto/repo/schema.ex:193: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
        (shield) web/controllers/shield/user_controller.ex:73: Shield.UserController.register/2
        (shield) web/controllers/shield/user_controller.ex:1: Shield.UserController.action/2
        (shield) web/controllers/shield/user_controller.ex:1: Shield.UserController.phoenix_controller_pipeline/2
        (cood_api_service) lib/cood_api_service/endpoint.ex:1: CoodApiService.Endpoint.instrument/4
        (cood_api_service) lib/phoenix/router.ex:261: CoodApiService.Router.dispatch/2
        (cood_api_service) web/router.ex:1: CoodApiService.Router.do_call/2
        (cood_api_service) lib/cood_api_service/endpoint.ex:1: CoodApiService.Endpoint.phoenix_pipeline/1
        (cood_api_service) lib/plug/debugger.ex:122: CoodApiService.Endpoint."call (overridable 3)"/2
        (cood_api_service) lib/cood_api_service/endpoint.ex:1: CoodApiService.Endpoint.call/2
```

My project is going to use mongodb_ecto + phoenix_ecto ~> 3.0 + shield ~> 0.3.3.
Maybe this problem is because of version conflict between mongodb_ecto and ecto ~> 2.0 or any others as I think.
Shield package needs ~> 2.0+, so I override ecto2.0 with override options in package.json as follows.
```
     {:mongodb_ecto, github: "michalmuskala/mongodb_ecto", branch: "ecto-2"},
     {:ecto, "~> 2.0", override: true},
     {:shield, "~> 0.3.3", github: "mustafaturan/shield"}
```
Could you help me with some guides to solve this problem? Thanks

**Comment by merqlove** [comment]
Use setup like this one:

```
{:phoenix_ecto, "~> 1.2.0", github: "merqlove/phoenix_ecto", branch: "v1.2.0.poison2"},
{:ecto, "~> 1.0.0", github: "merqlove/ecto", branch: "v1.0.poison2", override: true},
{:mongodb_ecto, "~> 0.1.4", github: "michalmuskala/mongodb_ecto", ref: "f8ddfaf2ac51d84d2074cd0a1d22acbdd4feeb38"}
```
2.0 branch is unstable

**Comment by michalmuskala** [comment]
The problem is not Elixir version, but Ecto version. This library does not support Ecto 2.0 yet. You can track the work being done in the two PRs: https://github.com/michalmuskala/mongodb_ecto/pull/91 https://github.com/michalmuskala/mongodb_ecto/pull/84
